package Interfaz;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Conexion.Conexion;
import Interfaz.*;
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas
 */
public class DM extends javax.swing.JFrame {
    Conexion con = new Conexion();
    int contador = 0;
    
    /**
     * Creates new form Citas
     */
    public DM() {
        initComponents();
        setLocationRelativeTo(null);
        
        //-------FONDO DE PANTALLA PRINCIPAL---------------
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Imagenes/fondo1.jpg")); 
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        
         GrupoElegir.add(rbAlergia);
         GrupoElegir.add(rbAltura);
         GrupoElegir.add(rbPadecimiento);
         GrupoElegir.add(rbPeso);
         txtBuscar.setVisible(false);
         cmbBuscar.setVisible(false);
         btnBuscar.setVisible(false);
    }
    
    void LlenarTabla(String sql, String[] datos){
        
        Connection connection = con.iniciarConexion();
        String valores[]=new String[5];
        
        DefaultTableModel modelo = new DefaultTableModel(null, datos);
        
        try {
            Statement st2 = connection.createStatement();
            ResultSet rs2 = st2.executeQuery(sql);
                    
            while (rs2.next()){
                 
                if(contador==0){
                 valores[0] = rs2.getString("NOMBRE");
                 valores[1] = rs2.getString("APELLIDO");
                 valores[2] = rs2.getString("ALTURA");
                 valores[3] = rs2.getString("PESO");  
                }else if(contador==1){
                    valores[0] = rs2.getString("NOMBRE");
                    valores[1] = rs2.getString("APELLIDO");
                    valores[2] = rs2.getString("PESO");
                }else if(contador==2){
                    valores[0] = rs2.getString("NOMBRE");
                    valores[1] = rs2.getString("APELLIDO");
                    valores[2] = rs2.getString("ALTURA");
                }
                 
                 modelo.addRow(valores);
            }
                        
        } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
        }
           
            TablaResultados.setModel(modelo);
            int[] anchos = {100, 80, 80,100};

            //hacemos un bucle FOR desde cero hasta la cantidad de columnas de nuestra tabla

            for(int i = 0; i < TablaResultados.getColumnCount(); i++) {
                TablaResultados.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoElegir = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JLabel();
        rbAlergia = new javax.swing.JRadioButton();
        rbPeso = new javax.swing.JRadioButton();
        rbPadecimiento = new javax.swing.JRadioButton();
        rbAltura = new javax.swing.JRadioButton();
        txtBuscar = new javax.swing.JTextField();
        cmbBuscar = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaResultados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel3.setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 11, -1, -1));

        rbAlergia.setText("Alergia");
        rbAlergia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAlergiaMouseClicked(evt);
            }
        });
        jPanel1.add(rbAlergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        rbPeso.setText("Peso");
        rbPeso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPesoMouseClicked(evt);
            }
        });
        jPanel1.add(rbPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 37, -1, -1));

        rbPadecimiento.setText("Padecimiento");
        rbPadecimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPadecimientoMouseClicked(evt);
            }
        });
        jPanel1.add(rbPadecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 37, -1, -1));

        rbAltura.setText("Altura");
        rbAltura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAlturaMouseClicked(evt);
            }
        });
        jPanel1.add(rbAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 11, -1, -1));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 12, 270, -1));

        jPanel1.add(cmbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 38, 270, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Historial");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        TablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaResultados);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap(638, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(10, 10, 10)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addContainerGap(379, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //this.hide();
        exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        String TextoBuscar = "";
        String ComboBuscar = "";
        
        
        String Tipo = "";
        String[] datos = new String [4];
        String[] datos1 = new String [3];
        
        if(rbAlergia.isSelected()){
             ComboBuscar = cmbBuscar.getSelectedItem().toString();
             datos[0] = "Nombre";
             datos[1] = "Apellido";
             datos[2] = "Altura";
             datos[3] = "Peso";
             contador=0;
             Tipo = "SELECT PERSONA.NOMBRE AS NOMBRE, PERSONA.PRIMER_APELLIDO AS APELLIDO, PACIENTE.ALTURA AS ALTURA, PACIENTE.PESO AS PESO FROM PERSONA, PACIENTE, ALERGIA_PACIENTE, ALERGIA WHERE ALERGIA_PACIENTE.CODIGO_ALERGIA = ALERGIA.CODIGO_ALERGIA AND ALERGIA_PACIENTE.CODIGO_PACIENTE = PACIENTE.CODIGO_PACIENTE AND PACIENTE.CODIGO_PERSONA = PERSONA.CODIGO_PERSONA AND ALERGIA.NOMBRE_ALERGIA = '"+ComboBuscar+"'";
             LlenarTabla(Tipo, datos);
        }else if(rbPadecimiento.isSelected()){
             ComboBuscar = cmbBuscar.getSelectedItem().toString();
             datos[0] = "Nombre";
             datos[1] = "Apellido";
             datos[2] = "Altura";
             datos[3] = "Peso";
             contador=0;
            Tipo = "SELECT PERSONA.NOMBRE AS NOMBRE, PERSONA.PRIMER_APELLIDO AS APELLIDO, PACIENTE.ALTURA AS ALTURA, PACIENTE.PESO AS PESO FROM PERSONA, PACIENTE, PADECIMIENTO_PACIENTE, PADECIMIENTO WHERE PADECIMIENTO_PACIENTE.CODIGO_PADECIMIENTO = PADECIMIENTO.CODIGO_PADECIMIENTO AND PADECIMIENTO_PACIENTE.CODIGO_PACIENTE = PACIENTE.CODIGO_PACIENTE AND PACIENTE.CODIGO_PERSONA = PERSONA.CODIGO_PERSONA AND PADECIMIENTO.NOMBRE_PADECIMIENTO = '"+ComboBuscar+"'";
            LlenarTabla(Tipo, datos);
        }else if(rbAltura.isSelected()){
             TextoBuscar = txtBuscar.getText();
             datos1[0] = "Nombre";
             datos1[1] = "Apellido";
             datos1[2] = "Peso";
             contador=1;
            Tipo = "SELECT PERSONA.NOMBRE AS NOMBRE, PERSONA.PRIMER_APELLIDO AS APELLIDO, PACIENTE.PESO AS PESO FROM PERSONA, PACIENTE WHERE PACIENTE.CODIGO_PERSONA = PERSONA.CODIGO_PERSONA AND PACIENTE.ALTURA = '"+TextoBuscar+"'";
            LlenarTabla(Tipo, datos1);
        }else if(rbPeso.isSelected()){
             TextoBuscar = txtBuscar.getText();
             datos1[0] = "Nombre";
             datos1[1] = "Apellido";
             datos1[2] = "Altura";
             contador=2;
            Tipo = "SELECT PERSONA.NOMBRE AS NOMBRE, PERSONA.PRIMER_APELLIDO AS APELLIDO, PACIENTE.ALTURA AS ALTURA FROM PERSONA, PACIENTE WHERE PACIENTE.CODIGO_PERSONA = PERSONA.CODIGO_PERSONA AND PACIENTE.PESO = '"+TextoBuscar+"'";
            LlenarTabla(Tipo, datos1);
        }
        
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void rbAlergiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAlergiaMouseClicked
        // TODO add your handling code here:
        cmbBuscar.removeAllItems();
        btnBuscar.setVisible(true);
        cmbBuscar.setVisible(true);
        txtBuscar.setVisible(false);
        Connection connection = con.iniciarConexion();
        String Alergia = "";
        String sql = "SELECT NOMBRE_ALERGIA FROM ALERGIA";
        
            
           try {
            Statement st2 = connection.createStatement();
            ResultSet rs2 = st2.executeQuery(sql);
                    
            while (rs2.next()){
                 Alergia = rs2.getString("NOMBRE_ALERGIA");
                 cmbBuscar.addItem(Alergia);
                 Alergia = "";
                 
            }
                        
        } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_rbAlergiaMouseClicked

    private void rbPadecimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPadecimientoMouseClicked
        // TODO add your handling code here:
        cmbBuscar.removeAllItems();
        btnBuscar.setVisible(true);
        cmbBuscar.setVisible(true);
        txtBuscar.setVisible(false);
        Connection connection = con.iniciarConexion();
        String Padecimiento = "";
        String sql = "SELECT NOMBRE_PADECIMIENTO FROM PADECIMIENTO";
        
            
           try {
            Statement st2 = connection.createStatement();
            ResultSet rs2 = st2.executeQuery(sql);
                    
            while (rs2.next()){
                 Padecimiento = rs2.getString("NOMBRE_PADECIMIENTO");
                 cmbBuscar.addItem(Padecimiento);
                 Padecimiento = "";
                 
            }
                        
        } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_rbPadecimientoMouseClicked

    private void rbPesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPesoMouseClicked
        // TODO add your handling code here:
        
        cmbBuscar.setVisible(false);
        btnBuscar.setVisible(true);
        txtBuscar.setVisible(true);
    }//GEN-LAST:event_rbPesoMouseClicked

    private void rbAlturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAlturaMouseClicked
        // TODO add your handling code here:
        cmbBuscar.setVisible(false);
        btnBuscar.setVisible(true);
        txtBuscar.setVisible(true);
        
    }//GEN-LAST:event_rbAlturaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoElegir;
    private javax.swing.JTable TablaResultados;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JComboBox cmbBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbAlergia;
    private javax.swing.JRadioButton rbAltura;
    private javax.swing.JRadioButton rbPadecimiento;
    private javax.swing.JRadioButton rbPeso;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
