/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import static java.lang.System.exit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import Conexion.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas
 */
public class Inicio extends javax.swing.JFrame {
    
    Conexion con = new Conexion();


    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
        setLocationRelativeTo(null);
        //-------FONDO DE PANTALLA PRINCIPAL---------------
        //((JPanel)getContentPane()).setOpaque(false); 
        //ImageIcon uno=new ImageIcon(this.getClass().getResource("/Imagenes/login.jpg")); 
        //JLabel fondo= new JLabel(); 
        //fondo.setIcon(uno); 
        //getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        //fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        txtUsuario.setText("Usuario");
        txtPassword.setText("Password");
        lbl_entrar.requestFocus();
        
        
    }
    
    void limpiar(){
        if(txtUsuario.getText().equals("Usuario")){
            txtUsuario.setText("");    
        }
    }
    
    void limpiar2(){
        if(txtPassword.getText().equals("Password")){
            txtPassword.setText("");    
        }
    }
    
    
    boolean ConsultaAdmin(){
        
        Connection connection = con.iniciarConexion();
        
        String Password = txtPassword.getText().trim();
        String NombreUsuario = txtUsuario.getText().toLowerCase().trim();
        
        boolean encontro=false;
        String codigo="";
        
        String sql = "SELECT CODIGO_USUARIO FROM LOGIN WHERE PASSWORD = '"+Password+"' AND USUARIO = '"+NombreUsuario+"'";
        
         
         try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);
                    
            while (rs.next()){
                codigo = rs.getString("CODIGO_USUARIO");
                encontro=true;
            }
                        
        } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
        }
        
        return encontro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_exit = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lbl_entrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        txtUsuario.setToolTipText("Ingrese el nombre de su usuario");
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 165, 180, 30));
        txtUsuario.getAccessibleContext().setAccessibleName("");

        txtPassword.setToolTipText("Ingrese su contraseña");
        txtPassword.setPreferredSize(new java.awt.Dimension(76, 25));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 205, 180, 30));

        lbl_entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login_button.png"))); // NOI18N
        lbl_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_entrarMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 260, 60, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        // TODO add your handling code here:
        limpiar();
        
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        limpiar2();
        
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        // TODO add your handling code here:
        if(txtUsuario.getText().equals("")){
            txtUsuario.setText("Usuario");
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
        if(txtPassword.getText().equals("")){
            txtPassword.setText("Password");
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_entrarMouseClicked
        // TODO add your handling code here:
        String Usuario = txtUsuario.getText().toLowerCase();
        String Password = txtPassword.getText();
         if(Usuario.equals("admin") && (Password.equals("admin"))){
                MenuPrincipal adm = new MenuPrincipal(); 
                    adm.setVisible(true);
                    this.hide();
            
        }else if(Usuario.equals("operador") && (Password.equals("operador"))) {
            
            
        }else{
                 JOptionPane.showMessageDialog(null,"Acceso Denegado","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lbl_entrarMouseClicked

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        // TODO add your handling code here:
       if(txtUsuario.getText().equals("Usuario")){
           txtUsuario.setText("");
       }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        // TODO add your handling code here:
        if(txtPassword.getText().equals("Password")){
            txtPassword.setText("");
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_entrar;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
