/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import static java.lang.System.exit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Douglas
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        //-------FONDO DE PANTALLA PRINCIPAL---------------
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Imagenes/fondo1.jpg")); 
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Barra_menu = new javax.swing.JMenuBar();
        menu_paciente = new javax.swing.JMenu();
        submenu_nuevopaciente = new javax.swing.JMenuItem();
        menu_empleados = new javax.swing.JMenu();
        submenu_agregarempleado = new javax.swing.JMenuItem();
        menu_citas = new javax.swing.JMenu();
        submenu_citas = new javax.swing.JMenuItem();
        submenu_buscarcitas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        submenu_crearconsulta = new javax.swing.JMenuItem();
        menu_habitacion = new javax.swing.JMenu();
        submenu_reghabitacion = new javax.swing.JMenuItem();
        menu_informe = new javax.swing.JMenu();
        submenu_informepaciente = new javax.swing.JMenuItem();
        submenu_verinforme = new javax.swing.JMenuItem();
        menu_inventario = new javax.swing.JMenu();
        submenu_listarinventario = new javax.swing.JMenuItem();
        submenu_agregarinventario = new javax.swing.JMenuItem();
        menu_historial = new javax.swing.JMenu();
        menu_opcion = new javax.swing.JMenu();
        submenu_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/culebrita.png"))); // NOI18N

        menu_paciente.setText("Paciente");

        submenu_nuevopaciente.setText("Nuevo Paciente");
        submenu_nuevopaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_nuevopacienteActionPerformed(evt);
            }
        });
        menu_paciente.add(submenu_nuevopaciente);

        Barra_menu.add(menu_paciente);

        menu_empleados.setText("Empleados");

        submenu_agregarempleado.setText("Agregar Empleado");
        submenu_agregarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_agregarempleadoActionPerformed(evt);
            }
        });
        menu_empleados.add(submenu_agregarempleado);

        Barra_menu.add(menu_empleados);

        menu_citas.setText("Citas");

        submenu_citas.setText("Crear Cita");
        submenu_citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_citasActionPerformed(evt);
            }
        });
        menu_citas.add(submenu_citas);

        submenu_buscarcitas.setText("Buscar Citas");
        submenu_buscarcitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_buscarcitasActionPerformed(evt);
            }
        });
        menu_citas.add(submenu_buscarcitas);

        Barra_menu.add(menu_citas);

        jMenu1.setText("Consulta");

        submenu_crearconsulta.setText("Crear Consulta");
        submenu_crearconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_crearconsultaActionPerformed(evt);
            }
        });
        jMenu1.add(submenu_crearconsulta);

        Barra_menu.add(jMenu1);

        menu_habitacion.setText("Habitacion");

        submenu_reghabitacion.setText("Registrar Habitacion");
        submenu_reghabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submenu_reghabitacionMouseClicked(evt);
            }
        });
        submenu_reghabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_reghabitacionActionPerformed(evt);
            }
        });
        menu_habitacion.add(submenu_reghabitacion);

        Barra_menu.add(menu_habitacion);

        menu_informe.setText("Informe");

        submenu_informepaciente.setText("Agregar Informe");
        submenu_informepaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_informepacienteActionPerformed(evt);
            }
        });
        menu_informe.add(submenu_informepaciente);

        submenu_verinforme.setText("Ver Informe");
        submenu_verinforme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submenu_verinformeMouseClicked(evt);
            }
        });
        submenu_verinforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_verinformeActionPerformed(evt);
            }
        });
        menu_informe.add(submenu_verinforme);

        Barra_menu.add(menu_informe);

        menu_inventario.setText("Inventario");

        submenu_listarinventario.setText("Listar Inventario");
        submenu_listarinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_listarinventarioActionPerformed(evt);
            }
        });
        menu_inventario.add(submenu_listarinventario);

        submenu_agregarinventario.setText("Agregar Producto");
        submenu_agregarinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_agregarinventarioActionPerformed(evt);
            }
        });
        menu_inventario.add(submenu_agregarinventario);

        Barra_menu.add(menu_inventario);

        menu_historial.setText("Historial");
        Barra_menu.add(menu_historial);

        menu_opcion.setText("Opciones");

        submenu_salir.setText("Salir");
        submenu_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submenu_salirMouseClicked(evt);
            }
        });
        submenu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_salirActionPerformed(evt);
            }
        });
        menu_opcion.add(submenu_salir);

        Barra_menu.add(menu_opcion);

        setJMenuBar(Barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenu_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submenu_salirMouseClicked
        // TODO add your handling code here:
        //System.exit(0);
    }//GEN-LAST:event_submenu_salirMouseClicked

    private void submenu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_salirActionPerformed
        // TODO add your handling code here:
        
        Object [] opciones ={"Aceptar","Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,"Esta seguro que desea cerrar la aplicacion","Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
        if (eleccion == JOptionPane.YES_OPTION){
            System.exit(0);
        }else{
        }
    }//GEN-LAST:event_submenu_salirActionPerformed

    private void submenu_nuevopacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_nuevopacienteActionPerformed
        // TODO add your handling code here:
        Pacientes ver = new Pacientes();
        ver.setVisible(true);
        //this.hide();
    }//GEN-LAST:event_submenu_nuevopacienteActionPerformed

    private void submenu_citasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_citasActionPerformed
        // TODO add your handling code here:
        Citas ver = new Citas();
        ver.setVisible(true);
    }//GEN-LAST:event_submenu_citasActionPerformed

    private void submenu_buscarcitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_buscarcitasActionPerformed
        // TODO add your handling code here:
        Consulta_Citas ver = new Consulta_Citas();
        ver.setVisible(true);
        
    }//GEN-LAST:event_submenu_buscarcitasActionPerformed

    private void submenu_reghabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submenu_reghabitacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submenu_reghabitacionMouseClicked

    private void submenu_reghabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_reghabitacionActionPerformed
        // TODO add your handling code here:
        Agregar_Habitacion ver = new Agregar_Habitacion();
        ver.setVisible(true);
    }//GEN-LAST:event_submenu_reghabitacionActionPerformed

    private void submenu_agregarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_agregarempleadoActionPerformed
        // TODO add your handling code here:
        Empleados ver = new Empleados();
        ver.setVisible(true);
    }//GEN-LAST:event_submenu_agregarempleadoActionPerformed

    private void submenu_crearconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_crearconsultaActionPerformed
        // TODO add your handling code here:
        Consulta ver = new Consulta();
        ver.setVisible(true);
    }//GEN-LAST:event_submenu_crearconsultaActionPerformed

    private void submenu_listarinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_listarinventarioActionPerformed
        // TODO add your handling code here:
        Inventario ver = new Inventario();
        ver.setVisible(true);
    }//GEN-LAST:event_submenu_listarinventarioActionPerformed

    private void submenu_agregarinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_agregarinventarioActionPerformed
        // TODO add your handling code here:
        Agregar_Inventario ver = new Agregar_Inventario();
        ver.setVisible(true);
    }//GEN-LAST:event_submenu_agregarinventarioActionPerformed

    private void submenu_informepacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_informepacienteActionPerformed
        // TODO add your handling code here:
        Informe_Paciente ver = new Informe_Paciente();
        ver.setVisible(true);
    }//GEN-LAST:event_submenu_informepacienteActionPerformed

    private void submenu_verinformeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submenu_verinformeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_submenu_verinformeMouseClicked

    private void submenu_verinformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_verinformeActionPerformed
        // TODO add your handling code here:
        new Buscar_Informe_Paciente().setVisible(true);
    }//GEN-LAST:event_submenu_verinformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu menu_citas;
    private javax.swing.JMenu menu_empleados;
    private javax.swing.JMenu menu_habitacion;
    private javax.swing.JMenu menu_historial;
    private javax.swing.JMenu menu_informe;
    private javax.swing.JMenu menu_inventario;
    private javax.swing.JMenu menu_opcion;
    private javax.swing.JMenu menu_paciente;
    private javax.swing.JMenuItem submenu_agregarempleado;
    private javax.swing.JMenuItem submenu_agregarinventario;
    private javax.swing.JMenuItem submenu_buscarcitas;
    private javax.swing.JMenuItem submenu_citas;
    private javax.swing.JMenuItem submenu_crearconsulta;
    private javax.swing.JMenuItem submenu_informepaciente;
    private javax.swing.JMenuItem submenu_listarinventario;
    private javax.swing.JMenuItem submenu_nuevopaciente;
    private javax.swing.JMenuItem submenu_reghabitacion;
    private javax.swing.JMenuItem submenu_salir;
    private javax.swing.JMenuItem submenu_verinforme;
    // End of variables declaration//GEN-END:variables
}
